server:
  port: 9900

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: ENSEIGNANT-SERVICE
        uri: lb://ENSEIGNANT-SERVICE
        predicates:
        - Path=/enseignant-service/**
      - id: IMPRESSION-SERVICE
        uri: lb://IMPRESSION-SERVICE
        predicates:
        - Path=/impression-service/**